//
//  PunkRallyBuildIdentity.swift
//  ink+amp
//
//  AltStore IPA identity stamp (America/New_York MMDDYY.HHmm).
//  Regenerated by scripts/stamp-build before CI / genxproj builds.
//
//  SPDX-License-Identifier: AGPL-3.0-only

import Foundation

public enum PunkRallyBuildIdentity {
    /// Placeholder overwritten by `scripts/stamp-build`. Keep parseable format.
    public static let stampSource = "000000.0000"

    public static var stamp: String {
        if stampSource != "000000.0000" { return stampSource }
        // Local/dev fallback: wall clock in America/New_York so Sideload still
        // shows something distinguishable when stamp-build was skipped.
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = TimeZone(identifier: "America/New_York") ?? .current
        let comps = calendar.dateComponents(
            [.month, .day, .year, .hour, .minute],
            from: Date()
        )
        let yy = (comps.year ?? 0) % 100
        return String(
            format: "%02d%02d%02d.%02d%02d",
            comps.month ?? 0,
            comps.day ?? 0,
            yy,
            comps.hour ?? 0,
            comps.minute ?? 0
        )
    }
}
